name: dungeonclub
description: An online platform to gather and play tabletop RPGs.
homepage: https://dungeonclub.net

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^3.4.9
  args: ^2.3.0
  async: ^2.8.2
  crypt: ^4.0.1
  googleapis_auth: ^1.3.0
  graceful: ^1.1.0
  grid_space:
    git: https://github.com/doodlezucc/dart_grid_space.git
  http: ^0.13.6
  image: ^4.0.17
  intl: ^0.19.0
  mailer: ^6.0.1
  meta: ^1.3.0
  path: ^1.7.0
  prompts: ^2.0.0
  random_string: ^2.1.0
  sass: ^1.64.1
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  yaml: ^3.1.2
  ambience:
    git: https://github.com/doodlezucc/ambience.git
  web_polymask:
    git: https://github.com/doodlezucc/web_polymask.git
  web_whiteboard:
    git: https://github.com/doodlezucc/web_whiteboard.git

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.5
  lints: ^3.0.0
  test: ^1.22.0
